ALTER TABLE addresses ADD COLUMN timezone TEXT;
ALTER TABLE addresses ADD COLUMN latitude DOUBLE PRECISION;
ALTER TABLE addresses ADD COLUMN longitude DOUBLE PRECISION;
ALTER TABLE addresses ADD COLUMN metro INTEGER;
ALTER TABLE addresses ADD COLUMN area DOUBLE PRECISION;
