import './landingpage.scss'
import '@client/components/hero/hero'
import '@client/components/feature_x1/feature_x1'
import '@client/components/feature_x2/feature_x2'
import '@client/components/cta/cta'
import '@client/components/footer/footer'
import '@client/components/redirect_link/redirect_link'
import '@client/ts/health_check_callout'
