// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Identifier type for public.addresses */
export type AddressesUuid = string & { __brand: 'public.addresses' };

/**
 * Represents the table public.addresses
 * Stores geographic locations associated with events.
 */
export default interface Addresses {
  /** Universally unique identifier for the address. */
  uuid: AddressesUuid;

  /** City of the address. */
  city: string | null;

  /** Region/State of the address. */
  region: string | null;

  /** Country of the address. */
  country: string | null;

  /** User who created the record. */
  created_by: string | null;

  /** Timestamp when the record was created. */
  created_date: Date | null;

  /** User who last updated the record. */
  updated_by: string | null;

  /** Timestamp when the record was last updated. */
  updated_date: Date | null;

  timezone: string | null;

  latitude: number | null;

  longitude: number | null;
}

/**
 * Represents the initializer for the table public.addresses
 * Stores geographic locations associated with events.
 */
export interface AddressesInitializer {
  /**
   * Universally unique identifier for the address.
   * Default value: uuid_generate_v4()
   */
  uuid?: AddressesUuid;

  /** City of the address. */
  city?: string | null;

  /** Region/State of the address. */
  region?: string | null;

  /** Country of the address. */
  country?: string | null;

  /** User who created the record. */
  created_by?: string | null;

  /** Timestamp when the record was created. */
  created_date?: Date | null;

  /** User who last updated the record. */
  updated_by?: string | null;

  /** Timestamp when the record was last updated. */
  updated_date?: Date | null;

  timezone?: string | null;

  latitude?: number | null;

  longitude?: number | null;
}

/**
 * Represents the mutator for the table public.addresses
 * Stores geographic locations associated with events.
 */
export interface AddressesMutator {
  /** Universally unique identifier for the address. */
  uuid?: AddressesUuid;

  /** City of the address. */
  city?: string | null;

  /** Region/State of the address. */
  region?: string | null;

  /** Country of the address. */
  country?: string | null;

  /** User who created the record. */
  created_by?: string | null;

  /** Timestamp when the record was created. */
  created_date?: Date | null;

  /** User who last updated the record. */
  updated_by?: string | null;

  /** Timestamp when the record was last updated. */
  updated_date?: Date | null;

  timezone?: string | null;

  latitude?: number | null;

  longitude?: number | null;
}

export const addressesUuid = z.string() as unknown as z.Schema<AddressesUuid>;

export const addresses = z.object({
  uuid: addressesUuid,
  city: z.string().nullable(),
  region: z.string().nullable(),
  country: z.string().nullable(),
  created_by: z.string().nullable(),
  created_date: z.date().nullable(),
  updated_by: z.string().nullable(),
  updated_date: z.date().nullable(),
  timezone: z.string().nullable(),
  latitude: z.number().nullable(),
  longitude: z.number().nullable(),
}) as unknown as z.Schema<Addresses>;

export const addressesInitializer = z.object({
  uuid: addressesUuid.optional(),
  city: z.string().optional().nullable(),
  region: z.string().optional().nullable(),
  country: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  created_date: z.date().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  updated_date: z.date().optional().nullable(),
  timezone: z.string().optional().nullable(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
}) as unknown as z.Schema<AddressesInitializer>;

export const addressesMutator = z.object({
  uuid: addressesUuid.optional(),
  city: z.string().optional().nullable(),
  region: z.string().optional().nullable(),
  country: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  created_date: z.date().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  updated_date: z.date().optional().nullable(),
  timezone: z.string().optional().nullable(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
}) as unknown as z.Schema<AddressesMutator>;
