// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the enum public.event_outcome */
enum EventOutcome {
  success = 'success',
  failure = 'failure',
};

export default EventOutcome;

/** Zod schema for event_outcome */
export const eventOutcome = z.enum([
  'success',
  'failure',
]);
