// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { contactsUuid, type ContactsUuid } from './Contacts';
import { addressesUuid, type AddressesUuid } from './Addresses';
import { eventOutcome, type default as EventOutcome } from './EventOutcome';
import { eventDirection, type default as EventDirection } from './EventDirection';
import { z } from 'zod';

/** Identifier type for public.events */
export type EventsUuid = string & { __brand: 'public.events' };

/**
 * Represents the table public.events
 * Tracks all events, including system-generated communications and user actions, even for anonymous visitors.
 */
export default interface Events {
  /** Universally unique identifier for the event. */
  uuid: EventsUuid;

  /** Reference to the contact involved in the event. Nullable for anonymous visitors. */
  contact_uuid: ContactsUuid | null;

  /** Reference to the geographic location (IP-based) of the event. */
  address_uuid: AddressesUuid | null;

  /** Generic origin of the event */
  origin: string | null;

  /** Describes the type of event */
  action: string;

  /** Outcome of the event, success or failure. */
  outcome: EventOutcome;

  /** Structured JSONB data capturing what happened, e.g., status codes, messages, or clicked URLs. */
  details: unknown | null;

  /** Timestamp indicating when the event took place. */
  occurred_at: Date;

  /** User who created the record. */
  created_by: string | null;

  /** Timestamp when the record was created. */
  created_date: Date | null;

  /** User who last updated the record. */
  updated_by: string | null;

  /** Timestamp when the record was last updated. */
  updated_date: Date | null;

  /** Stores a summary of the HTTP method and endpoint (e.g., "POST - /api/subscribe"). */
  endpoint: string | null;

  /** Specifies the direction of the event: inbound (incoming) or outbound (outgoing). */
  direction: EventDirection | null;
}

/**
 * Represents the initializer for the table public.events
 * Tracks all events, including system-generated communications and user actions, even for anonymous visitors.
 */
export interface EventsInitializer {
  /**
   * Universally unique identifier for the event.
   * Default value: uuid_generate_v4()
   */
  uuid?: EventsUuid;

  /** Reference to the contact involved in the event. Nullable for anonymous visitors. */
  contact_uuid?: ContactsUuid | null;

  /** Reference to the geographic location (IP-based) of the event. */
  address_uuid?: AddressesUuid | null;

  /** Generic origin of the event */
  origin?: string | null;

  /** Describes the type of event */
  action: string;

  /** Outcome of the event, success or failure. */
  outcome: EventOutcome;

  /** Structured JSONB data capturing what happened, e.g., status codes, messages, or clicked URLs. */
  details?: unknown | null;

  /** Timestamp indicating when the event took place. */
  occurred_at: Date;

  /** User who created the record. */
  created_by?: string | null;

  /** Timestamp when the record was created. */
  created_date?: Date | null;

  /** User who last updated the record. */
  updated_by?: string | null;

  /** Timestamp when the record was last updated. */
  updated_date?: Date | null;

  /** Stores a summary of the HTTP method and endpoint (e.g., "POST - /api/subscribe"). */
  endpoint?: string | null;

  /** Specifies the direction of the event: inbound (incoming) or outbound (outgoing). */
  direction?: EventDirection | null;
}

/**
 * Represents the mutator for the table public.events
 * Tracks all events, including system-generated communications and user actions, even for anonymous visitors.
 */
export interface EventsMutator {
  /** Universally unique identifier for the event. */
  uuid?: EventsUuid;

  /** Reference to the contact involved in the event. Nullable for anonymous visitors. */
  contact_uuid?: ContactsUuid | null;

  /** Reference to the geographic location (IP-based) of the event. */
  address_uuid?: AddressesUuid | null;

  /** Generic origin of the event */
  origin?: string | null;

  /** Describes the type of event */
  action?: string;

  /** Outcome of the event, success or failure. */
  outcome?: EventOutcome;

  /** Structured JSONB data capturing what happened, e.g., status codes, messages, or clicked URLs. */
  details?: unknown | null;

  /** Timestamp indicating when the event took place. */
  occurred_at?: Date;

  /** User who created the record. */
  created_by?: string | null;

  /** Timestamp when the record was created. */
  created_date?: Date | null;

  /** User who last updated the record. */
  updated_by?: string | null;

  /** Timestamp when the record was last updated. */
  updated_date?: Date | null;

  /** Stores a summary of the HTTP method and endpoint (e.g., "POST - /api/subscribe"). */
  endpoint?: string | null;

  /** Specifies the direction of the event: inbound (incoming) or outbound (outgoing). */
  direction?: EventDirection | null;
}

export const eventsUuid = z.string() as unknown as z.Schema<EventsUuid>;

export const events = z.object({
  uuid: eventsUuid,
  contact_uuid: contactsUuid.nullable(),
  address_uuid: addressesUuid.nullable(),
  origin: z.string().nullable(),
  action: z.string(),
  outcome: eventOutcome,
  details: z.unknown().nullable(),
  occurred_at: z.date(),
  created_by: z.string().nullable(),
  created_date: z.date().nullable(),
  updated_by: z.string().nullable(),
  updated_date: z.date().nullable(),
  endpoint: z.string().nullable(),
  direction: eventDirection.nullable(),
}) as unknown as z.Schema<Events>;

export const eventsInitializer = z.object({
  uuid: eventsUuid.optional(),
  contact_uuid: contactsUuid.optional().nullable(),
  address_uuid: addressesUuid.optional().nullable(),
  origin: z.string().optional().nullable(),
  action: z.string(),
  outcome: eventOutcome,
  details: z.unknown().optional().nullable(),
  occurred_at: z.date(),
  created_by: z.string().optional().nullable(),
  created_date: z.date().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  updated_date: z.date().optional().nullable(),
  endpoint: z.string().optional().nullable(),
  direction: eventDirection.optional().nullable(),
}) as unknown as z.Schema<EventsInitializer>;

export const eventsMutator = z.object({
  uuid: eventsUuid.optional(),
  contact_uuid: contactsUuid.optional().nullable(),
  address_uuid: addressesUuid.optional().nullable(),
  origin: z.string().optional().nullable(),
  action: z.string().optional(),
  outcome: eventOutcome.optional(),
  details: z.unknown().optional().nullable(),
  occurred_at: z.date().optional(),
  created_by: z.string().optional().nullable(),
  created_date: z.date().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  updated_date: z.date().optional().nullable(),
  endpoint: z.string().optional().nullable(),
  direction: eventDirection.optional().nullable(),
}) as unknown as z.Schema<EventsMutator>;
