// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the enum public.event_direction */
enum EventDirection {
  inbound = 'inbound',
  outbound = 'outbound',
};

export default EventDirection;

/** Zod schema for event_direction */
export const eventDirection = z.enum([
  'inbound',
  'outbound',
]);
