// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.addresses */
export type AddressesUuid = string & { __brand: 'AddressesUuid' };

/**
 * Represents the table public.addresses
 * Stores geographic locations associated with events.
 */
export default interface Addresses {
  /** Universally unique identifier for the address. */
  uuid: AddressesUuid;

  /** City of the address. */
  city: string | null;

  /** State/Region of the address. */
  state: string | null;

  /** Country of the address. */
  country: string | null;

  /** User who created the record. */
  created_by: string;

  /** Timestamp when the record was created. */
  created_date: Date;

  /** User who last updated the record. */
  updated_by: string;

  /** Timestamp when the record was last updated. */
  updated_date: Date;

  /** User who deleted the record. */
  deleted_by: string | null;

  /** Timestamp when the record was deleted. */
  deleted_date: Date | null;
}

/**
 * Represents the initializer for the table public.addresses
 * Stores geographic locations associated with events.
 */
export interface AddressesInitializer {
  /**
   * Universally unique identifier for the address.
   * Default value: uuid_generate_v4()
   */
  uuid?: AddressesUuid;

  /** City of the address. */
  city?: string | null;

  /** State/Region of the address. */
  state?: string | null;

  /** Country of the address. */
  country?: string | null;

  /** User who created the record. */
  created_by: string;

  /** Timestamp when the record was created. */
  created_date: Date;

  /** User who last updated the record. */
  updated_by: string;

  /** Timestamp when the record was last updated. */
  updated_date: Date;

  /** User who deleted the record. */
  deleted_by?: string | null;

  /** Timestamp when the record was deleted. */
  deleted_date?: Date | null;
}

/**
 * Represents the mutator for the table public.addresses
 * Stores geographic locations associated with events.
 */
export interface AddressesMutator {
  /** Universally unique identifier for the address. */
  uuid?: AddressesUuid;

  /** City of the address. */
  city?: string | null;

  /** State/Region of the address. */
  state?: string | null;

  /** Country of the address. */
  country?: string | null;

  /** User who created the record. */
  created_by?: string;

  /** Timestamp when the record was created. */
  created_date?: Date;

  /** User who last updated the record. */
  updated_by?: string;

  /** Timestamp when the record was last updated. */
  updated_date?: Date;

  /** User who deleted the record. */
  deleted_by?: string | null;

  /** Timestamp when the record was deleted. */
  deleted_date?: Date | null;
}
