// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.contact_status */
enum ContactStatus {
  lead = 'lead',
  prospect = 'prospect',
  customer = 'customer',
};

export default ContactStatus;
