// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.contact_subscriptions */
enum ContactSubscriptions {
  newsletter = 'newsletter',
};

export default ContactSubscriptions;
