// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.event_direction */
enum EventDirection {
  inbound = 'inbound',
  outbound = 'outbound',
};

export default EventDirection;
