// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ContactsUuid } from './Contacts';
import type { AddressesUuid } from './Addresses';
import type { default as EventOutcome } from './EventOutcome';
import type { default as EventDirection } from './EventDirection';

/** Identifier type for public.events */
export type EventsUuid = string & { __brand: 'EventsUuid' };

/**
 * Represents the table public.events
 * Tracks all events, including system-generated communications and user actions, even for anonymous visitors.
 */
export default interface Events {
  /** Universally unique identifier for the event. */
  uuid: EventsUuid;

  /** Reference to the contact involved in the event. Nullable for anonymous visitors. */
  contact_uuid: ContactsUuid | null;

  /** Reference to the geographic location (IP-based) of the event. */
  address_uuid: AddressesUuid | null;

  /** Generic origin of the event */
  origin: string | null;

  /** Describes the type of event */
  action: string;

  /** Outcome of the event, success or failure. */
  outcome: EventOutcome;

  /** Structured JSONB data capturing what happened, e.g., status codes, messages, or clicked URLs. */
  details: unknown | null;

  /** Timestamp indicating when the event took place. */
  occurred_at: Date;

  /** User who created the record. */
  created_by: string;

  /** Timestamp when the record was created. */
  created_date: Date;

  /** User who last updated the record. */
  updated_by: string;

  /** Timestamp when the record was last updated. */
  updated_date: Date;

  /** User who deleted the record. */
  deleted_by: string | null;

  /** Timestamp when the record was deleted. */
  deleted_date: Date | null;

  /** Stores a summary of the HTTP method and endpoint (e.g., "POST - /api/subscribe"). */
  endpoint: string | null;

  /** Specifies the direction of the event: inbound (incoming) or outbound (outgoing). */
  direction: EventDirection | null;
}

/**
 * Represents the initializer for the table public.events
 * Tracks all events, including system-generated communications and user actions, even for anonymous visitors.
 */
export interface EventsInitializer {
  /**
   * Universally unique identifier for the event.
   * Default value: uuid_generate_v4()
   */
  uuid?: EventsUuid;

  /** Reference to the contact involved in the event. Nullable for anonymous visitors. */
  contact_uuid?: ContactsUuid | null;

  /** Reference to the geographic location (IP-based) of the event. */
  address_uuid?: AddressesUuid | null;

  /** Generic origin of the event */
  origin?: string | null;

  /** Describes the type of event */
  action: string;

  /** Outcome of the event, success or failure. */
  outcome: EventOutcome;

  /** Structured JSONB data capturing what happened, e.g., status codes, messages, or clicked URLs. */
  details?: unknown | null;

  /** Timestamp indicating when the event took place. */
  occurred_at: Date;

  /** User who created the record. */
  created_by: string;

  /** Timestamp when the record was created. */
  created_date: Date;

  /** User who last updated the record. */
  updated_by: string;

  /** Timestamp when the record was last updated. */
  updated_date: Date;

  /** User who deleted the record. */
  deleted_by?: string | null;

  /** Timestamp when the record was deleted. */
  deleted_date?: Date | null;

  /** Stores a summary of the HTTP method and endpoint (e.g., "POST - /api/subscribe"). */
  endpoint?: string | null;

  /** Specifies the direction of the event: inbound (incoming) or outbound (outgoing). */
  direction?: EventDirection | null;
}

/**
 * Represents the mutator for the table public.events
 * Tracks all events, including system-generated communications and user actions, even for anonymous visitors.
 */
export interface EventsMutator {
  /** Universally unique identifier for the event. */
  uuid?: EventsUuid;

  /** Reference to the contact involved in the event. Nullable for anonymous visitors. */
  contact_uuid?: ContactsUuid | null;

  /** Reference to the geographic location (IP-based) of the event. */
  address_uuid?: AddressesUuid | null;

  /** Generic origin of the event */
  origin?: string | null;

  /** Describes the type of event */
  action?: string;

  /** Outcome of the event, success or failure. */
  outcome?: EventOutcome;

  /** Structured JSONB data capturing what happened, e.g., status codes, messages, or clicked URLs. */
  details?: unknown | null;

  /** Timestamp indicating when the event took place. */
  occurred_at?: Date;

  /** User who created the record. */
  created_by?: string;

  /** Timestamp when the record was created. */
  created_date?: Date;

  /** User who last updated the record. */
  updated_by?: string;

  /** Timestamp when the record was last updated. */
  updated_date?: Date;

  /** User who deleted the record. */
  deleted_by?: string | null;

  /** Timestamp when the record was deleted. */
  deleted_date?: Date | null;

  /** Stores a summary of the HTTP method and endpoint (e.g., "POST - /api/subscribe"). */
  endpoint?: string | null;

  /** Specifies the direction of the event: inbound (incoming) or outbound (outgoing). */
  direction?: EventDirection | null;
}
