// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.event_outcome */
enum EventOutcome {
  success = 'success',
  failure = 'failure',
};

export default EventOutcome;
