// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { actionOutcome, type default as ActionOutcome } from './ActionOutcome';
import { actionDirection, type default as ActionDirection } from './ActionDirection';
import { z } from 'zod';

/** Represents the table public.actions_backup */
export default interface ActionsBackup {
  uuid: string | null;

  contact_uuid: string | null;

  address_uuid: string | null;

  origin: string | null;

  action: string | null;

  outcome: ActionOutcome | null;

  details: unknown | null;

  occurred_at: Date | null;

  created_by: string | null;

  created_date: Date | null;

  updated_by: string | null;

  updated_date: Date | null;

  endpoint: string | null;

  direction: ActionDirection | null;

  attribution_uuid: string | null;
}

/** Represents the initializer for the table public.actions_backup */
export interface ActionsBackupInitializer {
  uuid?: string | null;

  contact_uuid?: string | null;

  address_uuid?: string | null;

  origin?: string | null;

  action?: string | null;

  outcome?: ActionOutcome | null;

  details?: unknown | null;

  occurred_at?: Date | null;

  created_by?: string | null;

  created_date?: Date | null;

  updated_by?: string | null;

  updated_date?: Date | null;

  endpoint?: string | null;

  direction?: ActionDirection | null;

  attribution_uuid?: string | null;
}

/** Represents the mutator for the table public.actions_backup */
export interface ActionsBackupMutator {
  uuid?: string | null;

  contact_uuid?: string | null;

  address_uuid?: string | null;

  origin?: string | null;

  action?: string | null;

  outcome?: ActionOutcome | null;

  details?: unknown | null;

  occurred_at?: Date | null;

  created_by?: string | null;

  created_date?: Date | null;

  updated_by?: string | null;

  updated_date?: Date | null;

  endpoint?: string | null;

  direction?: ActionDirection | null;

  attribution_uuid?: string | null;
}

export const actionsBackup = z.object({
  uuid: z.string().nullable(),
  contact_uuid: z.string().nullable(),
  address_uuid: z.string().nullable(),
  origin: z.string().nullable(),
  action: z.string().nullable(),
  outcome: actionOutcome.nullable(),
  details: z.unknown().nullable(),
  occurred_at: z.date().nullable(),
  created_by: z.string().nullable(),
  created_date: z.date().nullable(),
  updated_by: z.string().nullable(),
  updated_date: z.date().nullable(),
  endpoint: z.string().nullable(),
  direction: actionDirection.nullable(),
  attribution_uuid: z.string().nullable(),
}) as unknown as z.Schema<ActionsBackup>;

export const actionsBackupInitializer = z.object({
  uuid: z.string().optional().nullable(),
  contact_uuid: z.string().optional().nullable(),
  address_uuid: z.string().optional().nullable(),
  origin: z.string().optional().nullable(),
  action: z.string().optional().nullable(),
  outcome: actionOutcome.optional().nullable(),
  details: z.unknown().optional().nullable(),
  occurred_at: z.date().optional().nullable(),
  created_by: z.string().optional().nullable(),
  created_date: z.date().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  updated_date: z.date().optional().nullable(),
  endpoint: z.string().optional().nullable(),
  direction: actionDirection.optional().nullable(),
  attribution_uuid: z.string().optional().nullable(),
}) as unknown as z.Schema<ActionsBackupInitializer>;

export const actionsBackupMutator = z.object({
  uuid: z.string().optional().nullable(),
  contact_uuid: z.string().optional().nullable(),
  address_uuid: z.string().optional().nullable(),
  origin: z.string().optional().nullable(),
  action: z.string().optional().nullable(),
  outcome: actionOutcome.optional().nullable(),
  details: z.unknown().optional().nullable(),
  occurred_at: z.date().optional().nullable(),
  created_by: z.string().optional().nullable(),
  created_date: z.date().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  updated_date: z.date().optional().nullable(),
  endpoint: z.string().optional().nullable(),
  direction: actionDirection.optional().nullable(),
  attribution_uuid: z.string().optional().nullable(),
}) as unknown as z.Schema<ActionsBackupMutator>;
