// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the enum public.action_outcome */
enum ActionOutcome {
  success = 'success',
  failure = 'failure',
};

export default ActionOutcome;

/** Zod schema for action_outcome */
export const actionOutcome = z.enum([
  'success',
  'failure',
]);
