// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the enum public.action_direction */
enum ActionDirection {
  inbound = 'inbound',
  outbound = 'outbound',
};

export default ActionDirection;

/** Zod schema for action_direction */
export const actionDirection = z.enum([
  'inbound',
  'outbound',
]);
