// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the table public.addresses_backup */
export default interface AddressesBackup {
  uuid: string | null;

  city: string | null;

  region: string | null;

  country: string | null;

  created_by: string | null;

  created_date: Date | null;

  updated_by: string | null;

  updated_date: Date | null;

  timezone: string | null;

  latitude: number | null;

  longitude: number | null;
}

/** Represents the initializer for the table public.addresses_backup */
export interface AddressesBackupInitializer {
  uuid?: string | null;

  city?: string | null;

  region?: string | null;

  country?: string | null;

  created_by?: string | null;

  created_date?: Date | null;

  updated_by?: string | null;

  updated_date?: Date | null;

  timezone?: string | null;

  latitude?: number | null;

  longitude?: number | null;
}

/** Represents the mutator for the table public.addresses_backup */
export interface AddressesBackupMutator {
  uuid?: string | null;

  city?: string | null;

  region?: string | null;

  country?: string | null;

  created_by?: string | null;

  created_date?: Date | null;

  updated_by?: string | null;

  updated_date?: Date | null;

  timezone?: string | null;

  latitude?: number | null;

  longitude?: number | null;
}

export const addressesBackup = z.object({
  uuid: z.string().nullable(),
  city: z.string().nullable(),
  region: z.string().nullable(),
  country: z.string().nullable(),
  created_by: z.string().nullable(),
  created_date: z.date().nullable(),
  updated_by: z.string().nullable(),
  updated_date: z.date().nullable(),
  timezone: z.string().nullable(),
  latitude: z.number().nullable(),
  longitude: z.number().nullable(),
}) as unknown as z.Schema<AddressesBackup>;

export const addressesBackupInitializer = z.object({
  uuid: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  region: z.string().optional().nullable(),
  country: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  created_date: z.date().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  updated_date: z.date().optional().nullable(),
  timezone: z.string().optional().nullable(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
}) as unknown as z.Schema<AddressesBackupInitializer>;

export const addressesBackupMutator = z.object({
  uuid: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  region: z.string().optional().nullable(),
  country: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  created_date: z.date().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  updated_date: z.date().optional().nullable(),
  timezone: z.string().optional().nullable(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
}) as unknown as z.Schema<AddressesBackupMutator>;
