// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/**
 * Represents the enum public.address_type
 * Defines the type of address: billing for payment info, shipping for delivery info
 */
enum AddressType {
  billing = 'billing',
  shipping = 'shipping',
};

export default AddressType;

/** Zod schema for address_type */
export const addressType = z.enum([
  'billing',
  'shipping',
]);
