// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { contactsUuid, type ContactsUuid } from './Contacts';
import { addressType, type default as AddressType } from './AddressType';
import { z } from 'zod';

/** Identifier type for public.addresses */
export type AddressesUuid = string & { __brand: 'public.addresses' };

/**
 * Represents the table public.addresses
 * Stores billing and shipping addresses for contacts, collected during checkout or profile updates
 */
export default interface Addresses {
  /** Universally unique identifier for the address */
  uuid: AddressesUuid;

  /** Reference to the contact who owns this address */
  contact_uuid: ContactsUuid;

  /** Type of address: billing for payment or shipping for delivery */
  type: AddressType;

  /** First line of the address (street address, PO Box, company name) */
  line1: string;

  /** Second line of the address (apartment, suite, unit, building, floor) */
  line2: string | null;

  /** City, district, suburb, town, or village */
  city: string | null;

  /** State, county, province, or region */
  state: string | null;

  /** ZIP or postal code */
  postal_code: string | null;

  /** Two-letter country code (ISO 3166-1 alpha-2) */
  country: string | null;

  /** Whether this is the default address of this type for the contact */
  is_default: boolean | null;

  /** Timestamp when the record was created */
  created_date: Date;

  /** Timestamp when the record was last updated */
  updated_date: Date | null;

  /** User who created the record */
  created_by: string | null;

  /** User who last updated the record */
  updated_by: string | null;

  /** User who deleted the record */
  deleted_by: string | null;

  /** Timestamp when the record was deleted */
  deleted_date: Date | null;

  /** Auto-incrementing serial number for easier data analysis and sequential referencing */
  auto_serial: number;
}

/**
 * Represents the initializer for the table public.addresses
 * Stores billing and shipping addresses for contacts, collected during checkout or profile updates
 */
export interface AddressesInitializer {
  /**
   * Universally unique identifier for the address
   * Default value: uuid_generate_v4()
   */
  uuid?: AddressesUuid;

  /** Reference to the contact who owns this address */
  contact_uuid: ContactsUuid;

  /** Type of address: billing for payment or shipping for delivery */
  type: AddressType;

  /** First line of the address (street address, PO Box, company name) */
  line1: string;

  /** Second line of the address (apartment, suite, unit, building, floor) */
  line2?: string | null;

  /** City, district, suburb, town, or village */
  city?: string | null;

  /** State, county, province, or region */
  state?: string | null;

  /** ZIP or postal code */
  postal_code?: string | null;

  /** Two-letter country code (ISO 3166-1 alpha-2) */
  country?: string | null;

  /**
   * Whether this is the default address of this type for the contact
   * Default value: false
   */
  is_default?: boolean | null;

  /**
   * Timestamp when the record was created
   * Default value: now()
   */
  created_date?: Date;

  /** Timestamp when the record was last updated */
  updated_date?: Date | null;

  /** User who created the record */
  created_by?: string | null;

  /** User who last updated the record */
  updated_by?: string | null;

  /** User who deleted the record */
  deleted_by?: string | null;

  /** Timestamp when the record was deleted */
  deleted_date?: Date | null;

  /**
   * Auto-incrementing serial number for easier data analysis and sequential referencing
   * Default value: nextval('addresses_auto_serial_seq'::regclass)
   */
  auto_serial?: number;
}

/**
 * Represents the mutator for the table public.addresses
 * Stores billing and shipping addresses for contacts, collected during checkout or profile updates
 */
export interface AddressesMutator {
  /** Universally unique identifier for the address */
  uuid?: AddressesUuid;

  /** Reference to the contact who owns this address */
  contact_uuid?: ContactsUuid;

  /** Type of address: billing for payment or shipping for delivery */
  type?: AddressType;

  /** First line of the address (street address, PO Box, company name) */
  line1?: string;

  /** Second line of the address (apartment, suite, unit, building, floor) */
  line2?: string | null;

  /** City, district, suburb, town, or village */
  city?: string | null;

  /** State, county, province, or region */
  state?: string | null;

  /** ZIP or postal code */
  postal_code?: string | null;

  /** Two-letter country code (ISO 3166-1 alpha-2) */
  country?: string | null;

  /** Whether this is the default address of this type for the contact */
  is_default?: boolean | null;

  /** Timestamp when the record was created */
  created_date?: Date;

  /** Timestamp when the record was last updated */
  updated_date?: Date | null;

  /** User who created the record */
  created_by?: string | null;

  /** User who last updated the record */
  updated_by?: string | null;

  /** User who deleted the record */
  deleted_by?: string | null;

  /** Timestamp when the record was deleted */
  deleted_date?: Date | null;

  /** Auto-incrementing serial number for easier data analysis and sequential referencing */
  auto_serial?: number;
}

export const addressesUuid = z.string() as unknown as z.Schema<AddressesUuid>;

export const addresses = z.object({
  uuid: addressesUuid,
  contact_uuid: contactsUuid,
  type: addressType,
  line1: z.string(),
  line2: z.string().nullable(),
  city: z.string().nullable(),
  state: z.string().nullable(),
  postal_code: z.string().nullable(),
  country: z.string().nullable(),
  is_default: z.boolean().nullable(),
  created_date: z.date(),
  updated_date: z.date().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable(),
  deleted_by: z.string().nullable(),
  deleted_date: z.date().nullable(),
  auto_serial: z.number(),
}) as unknown as z.Schema<Addresses>;

export const addressesInitializer = z.object({
  uuid: addressesUuid.optional(),
  contact_uuid: contactsUuid,
  type: addressType,
  line1: z.string(),
  line2: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  state: z.string().optional().nullable(),
  postal_code: z.string().optional().nullable(),
  country: z.string().optional().nullable(),
  is_default: z.boolean().optional().nullable(),
  created_date: z.date().optional(),
  updated_date: z.date().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  deleted_by: z.string().optional().nullable(),
  deleted_date: z.date().optional().nullable(),
  auto_serial: z.number().optional(),
}) as unknown as z.Schema<AddressesInitializer>;

export const addressesMutator = z.object({
  uuid: addressesUuid.optional(),
  contact_uuid: contactsUuid.optional(),
  type: addressType.optional(),
  line1: z.string().optional(),
  line2: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  state: z.string().optional().nullable(),
  postal_code: z.string().optional().nullable(),
  country: z.string().optional().nullable(),
  is_default: z.boolean().optional().nullable(),
  created_date: z.date().optional(),
  updated_date: z.date().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  deleted_by: z.string().optional().nullable(),
  deleted_date: z.date().optional().nullable(),
  auto_serial: z.number().optional(),
}) as unknown as z.Schema<AddressesMutator>;
