// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { analyticsEventName, type default as AnalyticsEventName } from './AnalyticsEventName';
import { z } from 'zod';

/** Identifier type for public.analytics_events */
export type AnalyticsEventsUuid = string & { __brand: 'public.analytics_events' };

/**
 * Represents the table public.analytics_events
 * Stores anonymous analytics events with denormalized data for high-volume tracking and fast aggregations.
 */
export default interface AnalyticsEvents {
  /** Universally unique identifier for the analytics event. */
  uuid: AnalyticsEventsUuid;

  /** Anonymous session identifier (e.g., generated client-side hash) - unique per browser session. */
  session_id: string | null;

  /** Anonymous visitor fingerprint for cross-session tracking - persists across sessions for same device/browser. */
  visitor_id: string | null;

  /** Type of analytics event being tracked. */
  event_name: AnalyticsEventName;

  /** Full URL of the page where the event occurred. */
  page_url: string | null;

  /** Title of the page where the event occurred. */
  page_title: string | null;

  /** Referrer URL that brought the user to this page. */
  page_referrer: string | null;

  /** UTM source parameter identifying the traffic source (e.g., google, facebook, newsletter). */
  utm_source: string | null;

  /** UTM medium parameter identifying the marketing medium (e.g., cpc, email, social). */
  utm_medium: string | null;

  /** UTM campaign parameter identifying the specific campaign name. */
  utm_campaign: string | null;

  /** UTM term parameter for paid search keywords. */
  utm_term: string | null;

  /** UTM content parameter for A/B testing and content-targeted ads. */
  utm_content: string | null;

  /** Browser user agent string for device and browser identification. */
  user_agent: string | null;

  /** Name of the browser (e.g., Chrome, Firefox, Safari). */
  browser_name: string | null;

  /** Version of the browser. */
  browser_version: string | null;

  /** Operating system name (e.g., Windows, macOS, Linux, Android, iOS). */
  os_name: string | null;

  /** Version of the operating system. */
  os_version: string | null;

  /** Type of device used (e.g., desktop, mobile, tablet). */
  device_type: string | null;

  /** Country where the event occurred. */
  country: string | null;

  /** Region/State where the event occurred. */
  region: string | null;

  /** City where the event occurred. */
  city: string | null;

  /** Timezone of the user when the event occurred. */
  timezone: string | null;

  /** Latitude coordinate of the event location. */
  latitude: number | null;

  /** Longitude coordinate of the event location. */
  longitude: number | null;

  /** Screen resolution of the user device (e.g., 1920x1080). */
  screen_resolution: string | null;

  /** Browser viewport size (e.g., 1440x900). */
  viewport_size: string | null;

  /** Browser language setting (e.g., it-IT, en-US). */
  language: string | null;

  /** Timestamp when the event actually occurred (can be different from created_date for batch processing). */
  occurred_at: Date;

  /** Timestamp when the record was created in the database. */
  created_date: Date;

  details: unknown | null;

  /** User who created the record. */
  created_by: string;

  /** User who last updated the record. */
  updated_by: string;

  /** Timestamp when the record was last updated. */
  updated_date: Date;

  /** Timestamp when the event occurred in the users local timezone - calculated server-side using client or IP-based timezone */
  local_occurred_at: Date | null;
}

/**
 * Represents the initializer for the table public.analytics_events
 * Stores anonymous analytics events with denormalized data for high-volume tracking and fast aggregations.
 */
export interface AnalyticsEventsInitializer {
  /**
   * Universally unique identifier for the analytics event.
   * Default value: uuid_generate_v4()
   */
  uuid?: AnalyticsEventsUuid;

  /** Anonymous session identifier (e.g., generated client-side hash) - unique per browser session. */
  session_id?: string | null;

  /** Anonymous visitor fingerprint for cross-session tracking - persists across sessions for same device/browser. */
  visitor_id?: string | null;

  /** Type of analytics event being tracked. */
  event_name: AnalyticsEventName;

  /** Full URL of the page where the event occurred. */
  page_url?: string | null;

  /** Title of the page where the event occurred. */
  page_title?: string | null;

  /** Referrer URL that brought the user to this page. */
  page_referrer?: string | null;

  /** UTM source parameter identifying the traffic source (e.g., google, facebook, newsletter). */
  utm_source?: string | null;

  /** UTM medium parameter identifying the marketing medium (e.g., cpc, email, social). */
  utm_medium?: string | null;

  /** UTM campaign parameter identifying the specific campaign name. */
  utm_campaign?: string | null;

  /** UTM term parameter for paid search keywords. */
  utm_term?: string | null;

  /** UTM content parameter for A/B testing and content-targeted ads. */
  utm_content?: string | null;

  /** Browser user agent string for device and browser identification. */
  user_agent?: string | null;

  /** Name of the browser (e.g., Chrome, Firefox, Safari). */
  browser_name?: string | null;

  /** Version of the browser. */
  browser_version?: string | null;

  /** Operating system name (e.g., Windows, macOS, Linux, Android, iOS). */
  os_name?: string | null;

  /** Version of the operating system. */
  os_version?: string | null;

  /** Type of device used (e.g., desktop, mobile, tablet). */
  device_type?: string | null;

  /** Country where the event occurred. */
  country?: string | null;

  /** Region/State where the event occurred. */
  region?: string | null;

  /** City where the event occurred. */
  city?: string | null;

  /** Timezone of the user when the event occurred. */
  timezone?: string | null;

  /** Latitude coordinate of the event location. */
  latitude?: number | null;

  /** Longitude coordinate of the event location. */
  longitude?: number | null;

  /** Screen resolution of the user device (e.g., 1920x1080). */
  screen_resolution?: string | null;

  /** Browser viewport size (e.g., 1440x900). */
  viewport_size?: string | null;

  /** Browser language setting (e.g., it-IT, en-US). */
  language?: string | null;

  /**
   * Timestamp when the event actually occurred (can be different from created_date for batch processing).
   * Default value: now()
   */
  occurred_at?: Date;

  /**
   * Timestamp when the record was created in the database.
   * Default value: now()
   */
  created_date?: Date;

  details?: unknown | null;

  /** User who created the record. */
  created_by: string;

  /** User who last updated the record. */
  updated_by: string;

  /** Timestamp when the record was last updated. */
  updated_date: Date;

  /** Timestamp when the event occurred in the users local timezone - calculated server-side using client or IP-based timezone */
  local_occurred_at?: Date | null;
}

/**
 * Represents the mutator for the table public.analytics_events
 * Stores anonymous analytics events with denormalized data for high-volume tracking and fast aggregations.
 */
export interface AnalyticsEventsMutator {
  /** Universally unique identifier for the analytics event. */
  uuid?: AnalyticsEventsUuid;

  /** Anonymous session identifier (e.g., generated client-side hash) - unique per browser session. */
  session_id?: string | null;

  /** Anonymous visitor fingerprint for cross-session tracking - persists across sessions for same device/browser. */
  visitor_id?: string | null;

  /** Type of analytics event being tracked. */
  event_name?: AnalyticsEventName;

  /** Full URL of the page where the event occurred. */
  page_url?: string | null;

  /** Title of the page where the event occurred. */
  page_title?: string | null;

  /** Referrer URL that brought the user to this page. */
  page_referrer?: string | null;

  /** UTM source parameter identifying the traffic source (e.g., google, facebook, newsletter). */
  utm_source?: string | null;

  /** UTM medium parameter identifying the marketing medium (e.g., cpc, email, social). */
  utm_medium?: string | null;

  /** UTM campaign parameter identifying the specific campaign name. */
  utm_campaign?: string | null;

  /** UTM term parameter for paid search keywords. */
  utm_term?: string | null;

  /** UTM content parameter for A/B testing and content-targeted ads. */
  utm_content?: string | null;

  /** Browser user agent string for device and browser identification. */
  user_agent?: string | null;

  /** Name of the browser (e.g., Chrome, Firefox, Safari). */
  browser_name?: string | null;

  /** Version of the browser. */
  browser_version?: string | null;

  /** Operating system name (e.g., Windows, macOS, Linux, Android, iOS). */
  os_name?: string | null;

  /** Version of the operating system. */
  os_version?: string | null;

  /** Type of device used (e.g., desktop, mobile, tablet). */
  device_type?: string | null;

  /** Country where the event occurred. */
  country?: string | null;

  /** Region/State where the event occurred. */
  region?: string | null;

  /** City where the event occurred. */
  city?: string | null;

  /** Timezone of the user when the event occurred. */
  timezone?: string | null;

  /** Latitude coordinate of the event location. */
  latitude?: number | null;

  /** Longitude coordinate of the event location. */
  longitude?: number | null;

  /** Screen resolution of the user device (e.g., 1920x1080). */
  screen_resolution?: string | null;

  /** Browser viewport size (e.g., 1440x900). */
  viewport_size?: string | null;

  /** Browser language setting (e.g., it-IT, en-US). */
  language?: string | null;

  /** Timestamp when the event actually occurred (can be different from created_date for batch processing). */
  occurred_at?: Date;

  /** Timestamp when the record was created in the database. */
  created_date?: Date;

  details?: unknown | null;

  /** User who created the record. */
  created_by?: string;

  /** User who last updated the record. */
  updated_by?: string;

  /** Timestamp when the record was last updated. */
  updated_date?: Date;

  /** Timestamp when the event occurred in the users local timezone - calculated server-side using client or IP-based timezone */
  local_occurred_at?: Date | null;
}

export const analyticsEventsUuid = z.string() as unknown as z.Schema<AnalyticsEventsUuid>;

export const analyticsEvents = z.object({
  uuid: analyticsEventsUuid,
  session_id: z.string().nullable(),
  visitor_id: z.string().nullable(),
  event_name: analyticsEventName,
  page_url: z.string().nullable(),
  page_title: z.string().nullable(),
  page_referrer: z.string().nullable(),
  utm_source: z.string().nullable(),
  utm_medium: z.string().nullable(),
  utm_campaign: z.string().nullable(),
  utm_term: z.string().nullable(),
  utm_content: z.string().nullable(),
  user_agent: z.string().nullable(),
  browser_name: z.string().nullable(),
  browser_version: z.string().nullable(),
  os_name: z.string().nullable(),
  os_version: z.string().nullable(),
  device_type: z.string().nullable(),
  country: z.string().nullable(),
  region: z.string().nullable(),
  city: z.string().nullable(),
  timezone: z.string().nullable(),
  latitude: z.number().nullable(),
  longitude: z.number().nullable(),
  screen_resolution: z.string().nullable(),
  viewport_size: z.string().nullable(),
  language: z.string().nullable(),
  occurred_at: z.date(),
  created_date: z.date(),
  details: z.unknown().nullable(),
  created_by: z.string(),
  updated_by: z.string(),
  updated_date: z.date(),
  local_occurred_at: z.date().nullable(),
}) as unknown as z.Schema<AnalyticsEvents>;

export const analyticsEventsInitializer = z.object({
  uuid: analyticsEventsUuid.optional(),
  session_id: z.string().optional().nullable(),
  visitor_id: z.string().optional().nullable(),
  event_name: analyticsEventName,
  page_url: z.string().optional().nullable(),
  page_title: z.string().optional().nullable(),
  page_referrer: z.string().optional().nullable(),
  utm_source: z.string().optional().nullable(),
  utm_medium: z.string().optional().nullable(),
  utm_campaign: z.string().optional().nullable(),
  utm_term: z.string().optional().nullable(),
  utm_content: z.string().optional().nullable(),
  user_agent: z.string().optional().nullable(),
  browser_name: z.string().optional().nullable(),
  browser_version: z.string().optional().nullable(),
  os_name: z.string().optional().nullable(),
  os_version: z.string().optional().nullable(),
  device_type: z.string().optional().nullable(),
  country: z.string().optional().nullable(),
  region: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  timezone: z.string().optional().nullable(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  screen_resolution: z.string().optional().nullable(),
  viewport_size: z.string().optional().nullable(),
  language: z.string().optional().nullable(),
  occurred_at: z.date().optional(),
  created_date: z.date().optional(),
  details: z.unknown().optional().nullable(),
  created_by: z.string(),
  updated_by: z.string(),
  updated_date: z.date(),
  local_occurred_at: z.date().optional().nullable(),
}) as unknown as z.Schema<AnalyticsEventsInitializer>;

export const analyticsEventsMutator = z.object({
  uuid: analyticsEventsUuid.optional(),
  session_id: z.string().optional().nullable(),
  visitor_id: z.string().optional().nullable(),
  event_name: analyticsEventName.optional(),
  page_url: z.string().optional().nullable(),
  page_title: z.string().optional().nullable(),
  page_referrer: z.string().optional().nullable(),
  utm_source: z.string().optional().nullable(),
  utm_medium: z.string().optional().nullable(),
  utm_campaign: z.string().optional().nullable(),
  utm_term: z.string().optional().nullable(),
  utm_content: z.string().optional().nullable(),
  user_agent: z.string().optional().nullable(),
  browser_name: z.string().optional().nullable(),
  browser_version: z.string().optional().nullable(),
  os_name: z.string().optional().nullable(),
  os_version: z.string().optional().nullable(),
  device_type: z.string().optional().nullable(),
  country: z.string().optional().nullable(),
  region: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  timezone: z.string().optional().nullable(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  screen_resolution: z.string().optional().nullable(),
  viewport_size: z.string().optional().nullable(),
  language: z.string().optional().nullable(),
  occurred_at: z.date().optional(),
  created_date: z.date().optional(),
  details: z.unknown().optional().nullable(),
  created_by: z.string().optional(),
  updated_by: z.string().optional(),
  updated_date: z.date().optional(),
  local_occurred_at: z.date().optional().nullable(),
}) as unknown as z.Schema<AnalyticsEventsMutator>;
