// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the table public.attributions_backup */
export default interface AttributionsBackup {
  uuid: string | null;

  utm_source: string | null;

  utm_medium: string | null;

  utm_campaign: string | null;

  utm_term: string | null;

  utm_content: string | null;

  created_by: string | null;

  created_date: Date | null;

  updated_by: string | null;

  updated_date: Date | null;
}

/** Represents the initializer for the table public.attributions_backup */
export interface AttributionsBackupInitializer {
  uuid?: string | null;

  utm_source?: string | null;

  utm_medium?: string | null;

  utm_campaign?: string | null;

  utm_term?: string | null;

  utm_content?: string | null;

  created_by?: string | null;

  created_date?: Date | null;

  updated_by?: string | null;

  updated_date?: Date | null;
}

/** Represents the mutator for the table public.attributions_backup */
export interface AttributionsBackupMutator {
  uuid?: string | null;

  utm_source?: string | null;

  utm_medium?: string | null;

  utm_campaign?: string | null;

  utm_term?: string | null;

  utm_content?: string | null;

  created_by?: string | null;

  created_date?: Date | null;

  updated_by?: string | null;

  updated_date?: Date | null;
}

export const attributionsBackup = z.object({
  uuid: z.string().nullable(),
  utm_source: z.string().nullable(),
  utm_medium: z.string().nullable(),
  utm_campaign: z.string().nullable(),
  utm_term: z.string().nullable(),
  utm_content: z.string().nullable(),
  created_by: z.string().nullable(),
  created_date: z.date().nullable(),
  updated_by: z.string().nullable(),
  updated_date: z.date().nullable(),
}) as unknown as z.Schema<AttributionsBackup>;

export const attributionsBackupInitializer = z.object({
  uuid: z.string().optional().nullable(),
  utm_source: z.string().optional().nullable(),
  utm_medium: z.string().optional().nullable(),
  utm_campaign: z.string().optional().nullable(),
  utm_term: z.string().optional().nullable(),
  utm_content: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  created_date: z.date().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  updated_date: z.date().optional().nullable(),
}) as unknown as z.Schema<AttributionsBackupInitializer>;

export const attributionsBackupMutator = z.object({
  uuid: z.string().optional().nullable(),
  utm_source: z.string().optional().nullable(),
  utm_medium: z.string().optional().nullable(),
  utm_campaign: z.string().optional().nullable(),
  utm_term: z.string().optional().nullable(),
  utm_content: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  created_date: z.date().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  updated_date: z.date().optional().nullable(),
}) as unknown as z.Schema<AttributionsBackupMutator>;
