// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Represents the enum public.contact_status */
enum ContactStatus {
  lead = 'lead',
  prospect = 'prospect',
  customer = 'customer',
};

export default ContactStatus;

/** Zod schema for contact_status */
export const contactStatus = z.enum([
  'lead',
  'prospect',
  'customer',
]);
