// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/** Identifier type for public.inbound_logs */
export type InboundLogsUuid = string & { __brand: 'public.inbound_logs' };

/**
 * Represents the table public.inbound_logs
 * Logs all inbound HTTP requests for debugging and analytics purposes
 */
export default interface InboundLogs {
  /** Universally unique identifier for the log entry */
  uuid: InboundLogsUuid;

  /** HTTP method (GET, POST, PUT, DELETE, etc.) */
  method: string;

  /** Full request URL including path and query string */
  url: string;

  /** HTTP request headers as JSON object (sensitive headers redacted) */
  headers: unknown | null;

  /** URL query parameters as JSON object */
  query_params: unknown | null;

  /** Request body as JSON (sensitive fields redacted) */
  body: unknown | null;

  /** Client IP address (supports IPv4 and IPv6) */
  ip_address: string | null;

  /** Client User-Agent string */
  user_agent: string | null;

  /** Timestamp when the request was received */
  occurred_at: Date;

  created_by: string | null;

  created_date: Date | null;

  updated_by: string | null;

  updated_date: Date | null;

  /** Auto-incrementing serial number for easier data analysis */
  auto_serial: number;
}

/**
 * Represents the initializer for the table public.inbound_logs
 * Logs all inbound HTTP requests for debugging and analytics purposes
 */
export interface InboundLogsInitializer {
  /**
   * Universally unique identifier for the log entry
   * Default value: uuid_generate_v4()
   */
  uuid?: InboundLogsUuid;

  /** HTTP method (GET, POST, PUT, DELETE, etc.) */
  method: string;

  /** Full request URL including path and query string */
  url: string;

  /** HTTP request headers as JSON object (sensitive headers redacted) */
  headers?: unknown | null;

  /** URL query parameters as JSON object */
  query_params?: unknown | null;

  /** Request body as JSON (sensitive fields redacted) */
  body?: unknown | null;

  /** Client IP address (supports IPv4 and IPv6) */
  ip_address?: string | null;

  /** Client User-Agent string */
  user_agent?: string | null;

  /**
   * Timestamp when the request was received
   * Default value: now()
   */
  occurred_at?: Date;

  created_by?: string | null;

  created_date?: Date | null;

  updated_by?: string | null;

  updated_date?: Date | null;

  /**
   * Auto-incrementing serial number for easier data analysis
   * Default value: nextval('inbound_logs_auto_serial_seq'::regclass)
   */
  auto_serial?: number;
}

/**
 * Represents the mutator for the table public.inbound_logs
 * Logs all inbound HTTP requests for debugging and analytics purposes
 */
export interface InboundLogsMutator {
  /** Universally unique identifier for the log entry */
  uuid?: InboundLogsUuid;

  /** HTTP method (GET, POST, PUT, DELETE, etc.) */
  method?: string;

  /** Full request URL including path and query string */
  url?: string;

  /** HTTP request headers as JSON object (sensitive headers redacted) */
  headers?: unknown | null;

  /** URL query parameters as JSON object */
  query_params?: unknown | null;

  /** Request body as JSON (sensitive fields redacted) */
  body?: unknown | null;

  /** Client IP address (supports IPv4 and IPv6) */
  ip_address?: string | null;

  /** Client User-Agent string */
  user_agent?: string | null;

  /** Timestamp when the request was received */
  occurred_at?: Date;

  created_by?: string | null;

  created_date?: Date | null;

  updated_by?: string | null;

  updated_date?: Date | null;

  /** Auto-incrementing serial number for easier data analysis */
  auto_serial?: number;
}

export const inboundLogsUuid = z.string() as unknown as z.Schema<InboundLogsUuid>;

export const inboundLogs = z.object({
  uuid: inboundLogsUuid,
  method: z.string(),
  url: z.string(),
  headers: z.unknown().nullable(),
  query_params: z.unknown().nullable(),
  body: z.unknown().nullable(),
  ip_address: z.string().nullable(),
  user_agent: z.string().nullable(),
  occurred_at: z.date(),
  created_by: z.string().nullable(),
  created_date: z.date().nullable(),
  updated_by: z.string().nullable(),
  updated_date: z.date().nullable(),
  auto_serial: z.number(),
}) as unknown as z.Schema<InboundLogs>;

export const inboundLogsInitializer = z.object({
  uuid: inboundLogsUuid.optional(),
  method: z.string(),
  url: z.string(),
  headers: z.unknown().optional().nullable(),
  query_params: z.unknown().optional().nullable(),
  body: z.unknown().optional().nullable(),
  ip_address: z.string().optional().nullable(),
  user_agent: z.string().optional().nullable(),
  occurred_at: z.date().optional(),
  created_by: z.string().optional().nullable(),
  created_date: z.date().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  updated_date: z.date().optional().nullable(),
  auto_serial: z.number().optional(),
}) as unknown as z.Schema<InboundLogsInitializer>;

export const inboundLogsMutator = z.object({
  uuid: inboundLogsUuid.optional(),
  method: z.string().optional(),
  url: z.string().optional(),
  headers: z.unknown().optional().nullable(),
  query_params: z.unknown().optional().nullable(),
  body: z.unknown().optional().nullable(),
  ip_address: z.string().optional().nullable(),
  user_agent: z.string().optional().nullable(),
  occurred_at: z.date().optional(),
  created_by: z.string().optional().nullable(),
  created_date: z.date().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  updated_date: z.date().optional().nullable(),
  auto_serial: z.number().optional(),
}) as unknown as z.Schema<InboundLogsMutator>;
