// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/**
 * Represents the enum public.order_status
 * Defines the final status of an order: paid (payment successful), failed (payment failed), canceled (order canceled), refunded (payment refunded).
 */
enum OrderStatus {
  paid = 'paid',
  failed = 'failed',
  canceled = 'canceled',
  refunded = 'refunded',
};

export default OrderStatus;

/** Zod schema for order_status */
export const orderStatus = z.enum([
  'paid',
  'failed',
  'canceled',
  'refunded',
]);
