// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { contactsUuid, type ContactsUuid } from './Contacts';
import { addressesUuid, type AddressesUuid } from './Addresses';
import { orderStatus, type default as OrderStatus } from './OrderStatus';
import { z } from 'zod';

/** Identifier type for public.orders */
export type OrdersUuid = string & { __brand: 'public.orders' };

/**
 * Represents the table public.orders
 * Stores customer orders with Stripe payment integration and tracking information
 */
export default interface Orders {
  /** Universally unique identifier for the order */
  uuid: OrdersUuid;

  /** Reference to the contact who placed the order, nullable if contact is deleted */
  contact_uuid: ContactsUuid | null;

  /** Email address of the customer, preserved even if contact is deleted */
  email: string;

  /** Stripe Checkout Session ID for tracking payment flow */
  stripe_session_id: string | null;

  /** Stripe Payment Intent ID for tracking payment status */
  stripe_payment_intent_id: string | null;

  /** Order total in major currency units (e.g., 1.00 USD). Previously stored as integer cents. */
  amount_total: string;

  /** Three-letter ISO currency code */
  currency: string;

  /** Reference to the billing address used for this order */
  billing_address_uuid: AddressesUuid | null;

  /** Reference to the shipping address used for this order */
  shipping_address_uuid: AddressesUuid | null;

  /** JSON array of purchased items from Stripe session */
  line_items: unknown | null;

  /** Timestamp when the order was placed */
  occurred_at: Date;

  /** Timestamp when the order was placed in the customer local timezone */
  local_occurred_at: Date | null;

  /** Timestamp when the record was created */
  created_date: Date;

  /** Timestamp when the record was last updated */
  updated_date: Date | null;

  /** User who created the record */
  created_by: string | null;

  /** User who last updated the record */
  updated_by: string | null;

  /** Auto-incrementing serial number for easier data analysis and sequential referencing */
  auto_serial: number;

  /** Current final status of the order - Set default to "failed" as a safety measure (though orders should always be created with explicit status) */
  status: OrderStatus;

  /** Full billing name captured at checkout (Stripe customer_details.name) */
  billing_name: string | null;

  /** Billing email captured at checkout (Stripe customer_details.email) */
  billing_email: string | null;

  /** Billing phone captured at checkout (Stripe customer_details.phone) */
  billing_phone: string | null;

  /** Billing country code (ISO-2) captured at checkout */
  billing_country: string | null;

  /** Billing state/region captured at checkout */
  billing_region: string | null;

  /** Billing city captured at checkout */
  billing_city: string | null;

  /** Billing postal/ZIP code captured at checkout */
  billing_postal_code: string | null;

  /** Billing address line 1 captured at checkout */
  billing_line1: string | null;

  /** Billing address line 2 captured at checkout */
  billing_line2: string | null;
}

/**
 * Represents the initializer for the table public.orders
 * Stores customer orders with Stripe payment integration and tracking information
 */
export interface OrdersInitializer {
  /**
   * Universally unique identifier for the order
   * Default value: uuid_generate_v4()
   */
  uuid?: OrdersUuid;

  /** Reference to the contact who placed the order, nullable if contact is deleted */
  contact_uuid?: ContactsUuid | null;

  /** Email address of the customer, preserved even if contact is deleted */
  email: string;

  /** Stripe Checkout Session ID for tracking payment flow */
  stripe_session_id?: string | null;

  /** Stripe Payment Intent ID for tracking payment status */
  stripe_payment_intent_id?: string | null;

  /** Order total in major currency units (e.g., 1.00 USD). Previously stored as integer cents. */
  amount_total: string;

  /**
   * Three-letter ISO currency code
   * Default value: 'USD'::bpchar
   */
  currency?: string;

  /** Reference to the billing address used for this order */
  billing_address_uuid?: AddressesUuid | null;

  /** Reference to the shipping address used for this order */
  shipping_address_uuid?: AddressesUuid | null;

  /** JSON array of purchased items from Stripe session */
  line_items?: unknown | null;

  /**
   * Timestamp when the order was placed
   * Default value: now()
   */
  occurred_at?: Date;

  /** Timestamp when the order was placed in the customer local timezone */
  local_occurred_at?: Date | null;

  /**
   * Timestamp when the record was created
   * Default value: now()
   */
  created_date?: Date;

  /** Timestamp when the record was last updated */
  updated_date?: Date | null;

  /** User who created the record */
  created_by?: string | null;

  /** User who last updated the record */
  updated_by?: string | null;

  /**
   * Auto-incrementing serial number for easier data analysis and sequential referencing
   * Default value: nextval('orders_auto_serial_seq'::regclass)
   */
  auto_serial?: number;

  /**
   * Current final status of the order - Set default to "failed" as a safety measure (though orders should always be created with explicit status)
   * Default value: 'failed'::order_status
   */
  status?: OrderStatus;

  /** Full billing name captured at checkout (Stripe customer_details.name) */
  billing_name?: string | null;

  /** Billing email captured at checkout (Stripe customer_details.email) */
  billing_email?: string | null;

  /** Billing phone captured at checkout (Stripe customer_details.phone) */
  billing_phone?: string | null;

  /** Billing country code (ISO-2) captured at checkout */
  billing_country?: string | null;

  /** Billing state/region captured at checkout */
  billing_region?: string | null;

  /** Billing city captured at checkout */
  billing_city?: string | null;

  /** Billing postal/ZIP code captured at checkout */
  billing_postal_code?: string | null;

  /** Billing address line 1 captured at checkout */
  billing_line1?: string | null;

  /** Billing address line 2 captured at checkout */
  billing_line2?: string | null;
}

/**
 * Represents the mutator for the table public.orders
 * Stores customer orders with Stripe payment integration and tracking information
 */
export interface OrdersMutator {
  /** Universally unique identifier for the order */
  uuid?: OrdersUuid;

  /** Reference to the contact who placed the order, nullable if contact is deleted */
  contact_uuid?: ContactsUuid | null;

  /** Email address of the customer, preserved even if contact is deleted */
  email?: string;

  /** Stripe Checkout Session ID for tracking payment flow */
  stripe_session_id?: string | null;

  /** Stripe Payment Intent ID for tracking payment status */
  stripe_payment_intent_id?: string | null;

  /** Order total in major currency units (e.g., 1.00 USD). Previously stored as integer cents. */
  amount_total?: string;

  /** Three-letter ISO currency code */
  currency?: string;

  /** Reference to the billing address used for this order */
  billing_address_uuid?: AddressesUuid | null;

  /** Reference to the shipping address used for this order */
  shipping_address_uuid?: AddressesUuid | null;

  /** JSON array of purchased items from Stripe session */
  line_items?: unknown | null;

  /** Timestamp when the order was placed */
  occurred_at?: Date;

  /** Timestamp when the order was placed in the customer local timezone */
  local_occurred_at?: Date | null;

  /** Timestamp when the record was created */
  created_date?: Date;

  /** Timestamp when the record was last updated */
  updated_date?: Date | null;

  /** User who created the record */
  created_by?: string | null;

  /** User who last updated the record */
  updated_by?: string | null;

  /** Auto-incrementing serial number for easier data analysis and sequential referencing */
  auto_serial?: number;

  /** Current final status of the order - Set default to "failed" as a safety measure (though orders should always be created with explicit status) */
  status?: OrderStatus;

  /** Full billing name captured at checkout (Stripe customer_details.name) */
  billing_name?: string | null;

  /** Billing email captured at checkout (Stripe customer_details.email) */
  billing_email?: string | null;

  /** Billing phone captured at checkout (Stripe customer_details.phone) */
  billing_phone?: string | null;

  /** Billing country code (ISO-2) captured at checkout */
  billing_country?: string | null;

  /** Billing state/region captured at checkout */
  billing_region?: string | null;

  /** Billing city captured at checkout */
  billing_city?: string | null;

  /** Billing postal/ZIP code captured at checkout */
  billing_postal_code?: string | null;

  /** Billing address line 1 captured at checkout */
  billing_line1?: string | null;

  /** Billing address line 2 captured at checkout */
  billing_line2?: string | null;
}

export const ordersUuid = z.string() as unknown as z.Schema<OrdersUuid>;

export const orders = z.object({
  uuid: ordersUuid,
  contact_uuid: contactsUuid.nullable(),
  email: z.string(),
  stripe_session_id: z.string().nullable(),
  stripe_payment_intent_id: z.string().nullable(),
  amount_total: z.string(),
  currency: z.string(),
  billing_address_uuid: addressesUuid.nullable(),
  shipping_address_uuid: addressesUuid.nullable(),
  line_items: z.unknown().nullable(),
  occurred_at: z.date(),
  local_occurred_at: z.date().nullable(),
  created_date: z.date(),
  updated_date: z.date().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable(),
  auto_serial: z.number(),
  status: orderStatus,
  billing_name: z.string().nullable(),
  billing_email: z.string().nullable(),
  billing_phone: z.string().nullable(),
  billing_country: z.string().nullable(),
  billing_region: z.string().nullable(),
  billing_city: z.string().nullable(),
  billing_postal_code: z.string().nullable(),
  billing_line1: z.string().nullable(),
  billing_line2: z.string().nullable(),
}) as unknown as z.Schema<Orders>;

export const ordersInitializer = z.object({
  uuid: ordersUuid.optional(),
  contact_uuid: contactsUuid.optional().nullable(),
  email: z.string(),
  stripe_session_id: z.string().optional().nullable(),
  stripe_payment_intent_id: z.string().optional().nullable(),
  amount_total: z.string(),
  currency: z.string().optional(),
  billing_address_uuid: addressesUuid.optional().nullable(),
  shipping_address_uuid: addressesUuid.optional().nullable(),
  line_items: z.unknown().optional().nullable(),
  occurred_at: z.date().optional(),
  local_occurred_at: z.date().optional().nullable(),
  created_date: z.date().optional(),
  updated_date: z.date().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  auto_serial: z.number().optional(),
  status: orderStatus.optional(),
  billing_name: z.string().optional().nullable(),
  billing_email: z.string().optional().nullable(),
  billing_phone: z.string().optional().nullable(),
  billing_country: z.string().optional().nullable(),
  billing_region: z.string().optional().nullable(),
  billing_city: z.string().optional().nullable(),
  billing_postal_code: z.string().optional().nullable(),
  billing_line1: z.string().optional().nullable(),
  billing_line2: z.string().optional().nullable(),
}) as unknown as z.Schema<OrdersInitializer>;

export const ordersMutator = z.object({
  uuid: ordersUuid.optional(),
  contact_uuid: contactsUuid.optional().nullable(),
  email: z.string().optional(),
  stripe_session_id: z.string().optional().nullable(),
  stripe_payment_intent_id: z.string().optional().nullable(),
  amount_total: z.string().optional(),
  currency: z.string().optional(),
  billing_address_uuid: addressesUuid.optional().nullable(),
  shipping_address_uuid: addressesUuid.optional().nullable(),
  line_items: z.unknown().optional().nullable(),
  occurred_at: z.date().optional(),
  local_occurred_at: z.date().optional().nullable(),
  created_date: z.date().optional(),
  updated_date: z.date().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  auto_serial: z.number().optional(),
  status: orderStatus.optional(),
  billing_name: z.string().optional().nullable(),
  billing_email: z.string().optional().nullable(),
  billing_phone: z.string().optional().nullable(),
  billing_country: z.string().optional().nullable(),
  billing_region: z.string().optional().nullable(),
  billing_city: z.string().optional().nullable(),
  billing_postal_code: z.string().optional().nullable(),
  billing_line1: z.string().optional().nullable(),
  billing_line2: z.string().optional().nullable(),
}) as unknown as z.Schema<OrdersMutator>;
