// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from 'zod';

/**
 * Represents the enum public.order_status
 * Defines the status of an order: pending (awaiting payment), paid (payment successful), failed (payment failed), refunded (payment refunded), canceled (order canceled)
 */
enum OrderStatus {
  pending = 'pending',
  paid = 'paid',
  failed = 'failed',
  refunded = 'refunded',
  canceled = 'canceled',
};

export default OrderStatus;

/** Zod schema for order_status */
export const orderStatus = z.enum([
  'pending',
  'paid',
  'failed',
  'refunded',
  'canceled',
]);
