// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { contactsUuid, type ContactsUuid } from './Contacts';
import { addressesUuid, type AddressesUuid } from './Addresses';
import { orderStatus, type default as OrderStatus } from './OrderStatus';
import { z } from 'zod';

/** Identifier type for public.orders */
export type OrdersUuid = string & { __brand: 'public.orders' };

/**
 * Represents the table public.orders
 * Stores customer orders with Stripe payment integration and tracking information
 */
export default interface Orders {
  /** Universally unique identifier for the order */
  uuid: OrdersUuid;

  /** Reference to the contact who placed the order, nullable if contact is deleted */
  contact_uuid: ContactsUuid | null;

  /** Email address of the customer, preserved even if contact is deleted */
  email: string;

  /** Stripe Checkout Session ID for tracking payment flow */
  stripe_session_id: string | null;

  /** Stripe Payment Intent ID for tracking payment status */
  stripe_payment_intent_id: string | null;

  /** Total amount charged in smallest currency unit (cents for USD) */
  amount_total: number;

  /** Three-letter ISO currency code */
  currency: string;

  /** Reference to the billing address used for this order */
  billing_address_uuid: AddressesUuid | null;

  /** Reference to the shipping address used for this order */
  shipping_address_uuid: AddressesUuid | null;

  /** JSON array of purchased items from Stripe session */
  line_items: unknown | null;

  /** UTM source parameter identifying the traffic source */
  utm_source: string | null;

  /** UTM medium parameter identifying the marketing medium */
  utm_medium: string | null;

  /** UTM campaign parameter identifying the specific campaign */
  utm_campaign: string | null;

  /** UTM term parameter for paid search keywords */
  utm_term: string | null;

  /** UTM content parameter for A/B testing and content-targeted ads */
  utm_content: string | null;

  /** Country where the order was placed */
  country: string | null;

  /** Region/State where the order was placed */
  region: string | null;

  /** City where the order was placed */
  city: string | null;

  /** Timezone where the order was placed */
  timezone: string | null;

  /** Latitude coordinate where the order was placed */
  latitude: number | null;

  /** Longitude coordinate where the order was placed */
  longitude: number | null;

  /** Timestamp when the order was placed */
  occurred_at: Date;

  /** Timestamp when the order was placed in the customer local timezone */
  local_occurred_at: Date | null;

  /** Timestamp when the record was created */
  created_date: Date;

  /** Timestamp when the record was last updated */
  updated_date: Date | null;

  /** User who created the record */
  created_by: string | null;

  /** User who last updated the record */
  updated_by: string | null;

  /** User who deleted the record */
  deleted_by: string | null;

  /** Timestamp when the record was deleted */
  deleted_date: Date | null;

  /** Auto-incrementing serial number for easier data analysis and sequential referencing */
  auto_serial: number;

  /** Current final status of the order - Set default to "failed" as a safety measure (though orders should always be created with explicit status) */
  status: OrderStatus;
}

/**
 * Represents the initializer for the table public.orders
 * Stores customer orders with Stripe payment integration and tracking information
 */
export interface OrdersInitializer {
  /**
   * Universally unique identifier for the order
   * Default value: uuid_generate_v4()
   */
  uuid?: OrdersUuid;

  /** Reference to the contact who placed the order, nullable if contact is deleted */
  contact_uuid?: ContactsUuid | null;

  /** Email address of the customer, preserved even if contact is deleted */
  email: string;

  /** Stripe Checkout Session ID for tracking payment flow */
  stripe_session_id?: string | null;

  /** Stripe Payment Intent ID for tracking payment status */
  stripe_payment_intent_id?: string | null;

  /** Total amount charged in smallest currency unit (cents for USD) */
  amount_total: number;

  /**
   * Three-letter ISO currency code
   * Default value: 'USD'::bpchar
   */
  currency?: string;

  /** Reference to the billing address used for this order */
  billing_address_uuid?: AddressesUuid | null;

  /** Reference to the shipping address used for this order */
  shipping_address_uuid?: AddressesUuid | null;

  /** JSON array of purchased items from Stripe session */
  line_items?: unknown | null;

  /** UTM source parameter identifying the traffic source */
  utm_source?: string | null;

  /** UTM medium parameter identifying the marketing medium */
  utm_medium?: string | null;

  /** UTM campaign parameter identifying the specific campaign */
  utm_campaign?: string | null;

  /** UTM term parameter for paid search keywords */
  utm_term?: string | null;

  /** UTM content parameter for A/B testing and content-targeted ads */
  utm_content?: string | null;

  /** Country where the order was placed */
  country?: string | null;

  /** Region/State where the order was placed */
  region?: string | null;

  /** City where the order was placed */
  city?: string | null;

  /** Timezone where the order was placed */
  timezone?: string | null;

  /** Latitude coordinate where the order was placed */
  latitude?: number | null;

  /** Longitude coordinate where the order was placed */
  longitude?: number | null;

  /**
   * Timestamp when the order was placed
   * Default value: now()
   */
  occurred_at?: Date;

  /** Timestamp when the order was placed in the customer local timezone */
  local_occurred_at?: Date | null;

  /**
   * Timestamp when the record was created
   * Default value: now()
   */
  created_date?: Date;

  /** Timestamp when the record was last updated */
  updated_date?: Date | null;

  /** User who created the record */
  created_by?: string | null;

  /** User who last updated the record */
  updated_by?: string | null;

  /** User who deleted the record */
  deleted_by?: string | null;

  /** Timestamp when the record was deleted */
  deleted_date?: Date | null;

  /**
   * Auto-incrementing serial number for easier data analysis and sequential referencing
   * Default value: nextval('orders_auto_serial_seq'::regclass)
   */
  auto_serial?: number;

  /**
   * Current final status of the order - Set default to "failed" as a safety measure (though orders should always be created with explicit status)
   * Default value: 'failed'::order_status
   */
  status?: OrderStatus;
}

/**
 * Represents the mutator for the table public.orders
 * Stores customer orders with Stripe payment integration and tracking information
 */
export interface OrdersMutator {
  /** Universally unique identifier for the order */
  uuid?: OrdersUuid;

  /** Reference to the contact who placed the order, nullable if contact is deleted */
  contact_uuid?: ContactsUuid | null;

  /** Email address of the customer, preserved even if contact is deleted */
  email?: string;

  /** Stripe Checkout Session ID for tracking payment flow */
  stripe_session_id?: string | null;

  /** Stripe Payment Intent ID for tracking payment status */
  stripe_payment_intent_id?: string | null;

  /** Total amount charged in smallest currency unit (cents for USD) */
  amount_total?: number;

  /** Three-letter ISO currency code */
  currency?: string;

  /** Reference to the billing address used for this order */
  billing_address_uuid?: AddressesUuid | null;

  /** Reference to the shipping address used for this order */
  shipping_address_uuid?: AddressesUuid | null;

  /** JSON array of purchased items from Stripe session */
  line_items?: unknown | null;

  /** UTM source parameter identifying the traffic source */
  utm_source?: string | null;

  /** UTM medium parameter identifying the marketing medium */
  utm_medium?: string | null;

  /** UTM campaign parameter identifying the specific campaign */
  utm_campaign?: string | null;

  /** UTM term parameter for paid search keywords */
  utm_term?: string | null;

  /** UTM content parameter for A/B testing and content-targeted ads */
  utm_content?: string | null;

  /** Country where the order was placed */
  country?: string | null;

  /** Region/State where the order was placed */
  region?: string | null;

  /** City where the order was placed */
  city?: string | null;

  /** Timezone where the order was placed */
  timezone?: string | null;

  /** Latitude coordinate where the order was placed */
  latitude?: number | null;

  /** Longitude coordinate where the order was placed */
  longitude?: number | null;

  /** Timestamp when the order was placed */
  occurred_at?: Date;

  /** Timestamp when the order was placed in the customer local timezone */
  local_occurred_at?: Date | null;

  /** Timestamp when the record was created */
  created_date?: Date;

  /** Timestamp when the record was last updated */
  updated_date?: Date | null;

  /** User who created the record */
  created_by?: string | null;

  /** User who last updated the record */
  updated_by?: string | null;

  /** User who deleted the record */
  deleted_by?: string | null;

  /** Timestamp when the record was deleted */
  deleted_date?: Date | null;

  /** Auto-incrementing serial number for easier data analysis and sequential referencing */
  auto_serial?: number;

  /** Current final status of the order - Set default to "failed" as a safety measure (though orders should always be created with explicit status) */
  status?: OrderStatus;
}

export const ordersUuid = z.string() as unknown as z.Schema<OrdersUuid>;

export const orders = z.object({
  uuid: ordersUuid,
  contact_uuid: contactsUuid.nullable(),
  email: z.string(),
  stripe_session_id: z.string().nullable(),
  stripe_payment_intent_id: z.string().nullable(),
  amount_total: z.number(),
  currency: z.string(),
  billing_address_uuid: addressesUuid.nullable(),
  shipping_address_uuid: addressesUuid.nullable(),
  line_items: z.unknown().nullable(),
  utm_source: z.string().nullable(),
  utm_medium: z.string().nullable(),
  utm_campaign: z.string().nullable(),
  utm_term: z.string().nullable(),
  utm_content: z.string().nullable(),
  country: z.string().nullable(),
  region: z.string().nullable(),
  city: z.string().nullable(),
  timezone: z.string().nullable(),
  latitude: z.number().nullable(),
  longitude: z.number().nullable(),
  occurred_at: z.date(),
  local_occurred_at: z.date().nullable(),
  created_date: z.date(),
  updated_date: z.date().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable(),
  deleted_by: z.string().nullable(),
  deleted_date: z.date().nullable(),
  auto_serial: z.number(),
  status: orderStatus,
}) as unknown as z.Schema<Orders>;

export const ordersInitializer = z.object({
  uuid: ordersUuid.optional(),
  contact_uuid: contactsUuid.optional().nullable(),
  email: z.string(),
  stripe_session_id: z.string().optional().nullable(),
  stripe_payment_intent_id: z.string().optional().nullable(),
  amount_total: z.number(),
  currency: z.string().optional(),
  billing_address_uuid: addressesUuid.optional().nullable(),
  shipping_address_uuid: addressesUuid.optional().nullable(),
  line_items: z.unknown().optional().nullable(),
  utm_source: z.string().optional().nullable(),
  utm_medium: z.string().optional().nullable(),
  utm_campaign: z.string().optional().nullable(),
  utm_term: z.string().optional().nullable(),
  utm_content: z.string().optional().nullable(),
  country: z.string().optional().nullable(),
  region: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  timezone: z.string().optional().nullable(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  occurred_at: z.date().optional(),
  local_occurred_at: z.date().optional().nullable(),
  created_date: z.date().optional(),
  updated_date: z.date().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  deleted_by: z.string().optional().nullable(),
  deleted_date: z.date().optional().nullable(),
  auto_serial: z.number().optional(),
  status: orderStatus.optional(),
}) as unknown as z.Schema<OrdersInitializer>;

export const ordersMutator = z.object({
  uuid: ordersUuid.optional(),
  contact_uuid: contactsUuid.optional().nullable(),
  email: z.string().optional(),
  stripe_session_id: z.string().optional().nullable(),
  stripe_payment_intent_id: z.string().optional().nullable(),
  amount_total: z.number().optional(),
  currency: z.string().optional(),
  billing_address_uuid: addressesUuid.optional().nullable(),
  shipping_address_uuid: addressesUuid.optional().nullable(),
  line_items: z.unknown().optional().nullable(),
  utm_source: z.string().optional().nullable(),
  utm_medium: z.string().optional().nullable(),
  utm_campaign: z.string().optional().nullable(),
  utm_term: z.string().optional().nullable(),
  utm_content: z.string().optional().nullable(),
  country: z.string().optional().nullable(),
  region: z.string().optional().nullable(),
  city: z.string().optional().nullable(),
  timezone: z.string().optional().nullable(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  occurred_at: z.date().optional(),
  local_occurred_at: z.date().optional().nullable(),
  created_date: z.date().optional(),
  updated_date: z.date().optional().nullable(),
  created_by: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  deleted_by: z.string().optional().nullable(),
  deleted_date: z.date().optional().nullable(),
  auto_serial: z.number().optional(),
  status: orderStatus.optional(),
}) as unknown as z.Schema<OrdersMutator>;
