// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { contactsUuid, type ContactsUuid } from './Contacts';
import { z } from 'zod';

/** Identifier type for public.webhook_logs */
export type WebhookLogsUuid = string & { __brand: 'public.webhook_logs' };

/**
 * Represents the table public.webhook_logs
 * Comprehensive logging of all webhook requests and responses for debugging and analytics
 */
export default interface WebhookLogs {
  uuid: WebhookLogsUuid;

  /** Source of the webhook (smtp2go, stripe, etc.) */
  webhook_source: string;

  request_method: string;

  request_url: string;

  request_headers: unknown | null;

  request_body: unknown | null;

  response_status: number | null;

  response_body: unknown | null;

  /** Result of webhook processing: success, contact_not_found, validation_error, processing_error */
  processing_outcome: string;

  /** Human-readable description of what happened during processing */
  processing_message: string | null;

  /** Technical error details including stack traces and validation errors */
  error_details: unknown | null;

  /** Reference to contact if found, NULL if contact not found */
  contact_uuid: ContactsUuid | null;

  /** Whether an action record was successfully created in the actions table */
  action_created: boolean | null;

  occurred_at: Date;

  local_occurred_at: Date | null;

  created_by: string | null;

  created_date: Date | null;

  updated_by: string | null;

  updated_date: Date | null;

  /** Sequential number for easier data analysis and referencing */
  auto_serial: number;
}

/**
 * Represents the initializer for the table public.webhook_logs
 * Comprehensive logging of all webhook requests and responses for debugging and analytics
 */
export interface WebhookLogsInitializer {
  /** Default value: uuid_generate_v4() */
  uuid?: WebhookLogsUuid;

  /** Source of the webhook (smtp2go, stripe, etc.) */
  webhook_source: string;

  request_method: string;

  request_url: string;

  request_headers?: unknown | null;

  request_body?: unknown | null;

  response_status?: number | null;

  response_body?: unknown | null;

  /** Result of webhook processing: success, contact_not_found, validation_error, processing_error */
  processing_outcome: string;

  /** Human-readable description of what happened during processing */
  processing_message?: string | null;

  /** Technical error details including stack traces and validation errors */
  error_details?: unknown | null;

  /** Reference to contact if found, NULL if contact not found */
  contact_uuid?: ContactsUuid | null;

  /**
   * Whether an action record was successfully created in the actions table
   * Default value: false
   */
  action_created?: boolean | null;

  /** Default value: now() */
  occurred_at?: Date;

  local_occurred_at?: Date | null;

  created_by?: string | null;

  created_date?: Date | null;

  updated_by?: string | null;

  updated_date?: Date | null;

  /**
   * Sequential number for easier data analysis and referencing
   * Default value: nextval('webhook_logs_auto_serial_seq'::regclass)
   */
  auto_serial?: number;
}

/**
 * Represents the mutator for the table public.webhook_logs
 * Comprehensive logging of all webhook requests and responses for debugging and analytics
 */
export interface WebhookLogsMutator {
  uuid?: WebhookLogsUuid;

  /** Source of the webhook (smtp2go, stripe, etc.) */
  webhook_source?: string;

  request_method?: string;

  request_url?: string;

  request_headers?: unknown | null;

  request_body?: unknown | null;

  response_status?: number | null;

  response_body?: unknown | null;

  /** Result of webhook processing: success, contact_not_found, validation_error, processing_error */
  processing_outcome?: string;

  /** Human-readable description of what happened during processing */
  processing_message?: string | null;

  /** Technical error details including stack traces and validation errors */
  error_details?: unknown | null;

  /** Reference to contact if found, NULL if contact not found */
  contact_uuid?: ContactsUuid | null;

  /** Whether an action record was successfully created in the actions table */
  action_created?: boolean | null;

  occurred_at?: Date;

  local_occurred_at?: Date | null;

  created_by?: string | null;

  created_date?: Date | null;

  updated_by?: string | null;

  updated_date?: Date | null;

  /** Sequential number for easier data analysis and referencing */
  auto_serial?: number;
}

export const webhookLogsUuid = z.string() as unknown as z.Schema<WebhookLogsUuid>;

export const webhookLogs = z.object({
  uuid: webhookLogsUuid,
  webhook_source: z.string(),
  request_method: z.string(),
  request_url: z.string(),
  request_headers: z.unknown().nullable(),
  request_body: z.unknown().nullable(),
  response_status: z.number().nullable(),
  response_body: z.unknown().nullable(),
  processing_outcome: z.string(),
  processing_message: z.string().nullable(),
  error_details: z.unknown().nullable(),
  contact_uuid: contactsUuid.nullable(),
  action_created: z.boolean().nullable(),
  occurred_at: z.date(),
  local_occurred_at: z.date().nullable(),
  created_by: z.string().nullable(),
  created_date: z.date().nullable(),
  updated_by: z.string().nullable(),
  updated_date: z.date().nullable(),
  auto_serial: z.number(),
}) as unknown as z.Schema<WebhookLogs>;

export const webhookLogsInitializer = z.object({
  uuid: webhookLogsUuid.optional(),
  webhook_source: z.string(),
  request_method: z.string(),
  request_url: z.string(),
  request_headers: z.unknown().optional().nullable(),
  request_body: z.unknown().optional().nullable(),
  response_status: z.number().optional().nullable(),
  response_body: z.unknown().optional().nullable(),
  processing_outcome: z.string(),
  processing_message: z.string().optional().nullable(),
  error_details: z.unknown().optional().nullable(),
  contact_uuid: contactsUuid.optional().nullable(),
  action_created: z.boolean().optional().nullable(),
  occurred_at: z.date().optional(),
  local_occurred_at: z.date().optional().nullable(),
  created_by: z.string().optional().nullable(),
  created_date: z.date().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  updated_date: z.date().optional().nullable(),
  auto_serial: z.number().optional(),
}) as unknown as z.Schema<WebhookLogsInitializer>;

export const webhookLogsMutator = z.object({
  uuid: webhookLogsUuid.optional(),
  webhook_source: z.string().optional(),
  request_method: z.string().optional(),
  request_url: z.string().optional(),
  request_headers: z.unknown().optional().nullable(),
  request_body: z.unknown().optional().nullable(),
  response_status: z.number().optional().nullable(),
  response_body: z.unknown().optional().nullable(),
  processing_outcome: z.string().optional(),
  processing_message: z.string().optional().nullable(),
  error_details: z.unknown().optional().nullable(),
  contact_uuid: contactsUuid.optional().nullable(),
  action_created: z.boolean().optional().nullable(),
  occurred_at: z.date().optional(),
  local_occurred_at: z.date().optional().nullable(),
  created_by: z.string().optional().nullable(),
  created_date: z.date().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  updated_date: z.date().optional().nullable(),
  auto_serial: z.number().optional(),
}) as unknown as z.Schema<WebhookLogsMutator>;
